AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Minimal SAM template for local Lambda development

Resources:
  ImageProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: image_processor/
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 30
      MemorySize: 512
